### ISSUE TITLE
you can run ?

### ISSUE THREAD

**Issue by solitarysp** [NLPL/NLPL-Tokenizer-Vietnamese#1]
you can run ?

**Comment by garfieldnate** [comment]
Hi Solitary, I have not done work on this project for a long time. I think it will not be useful to you right now. Please look at JVnTextPro: http://jvntextpro.sourceforge.net/.

If I have time to work on this soon, I will send you another message on how to use it.

**Comment by solitarysp** [comment]
hi Garfieldnate . Thank you , i has a project using analysis VietNamese language. I want validation word  when user input . If you know please share with me .

**Comment by garfieldnate** [comment]
Hi @solitarysp, I recently did some more work in this area. I forked JVnTextPro and released in on Maven Central/Jcenter. Please try it out. More details here: https://github.com/garfieldnate/JVnTextPro
